language: julia
julia:
    - release
    - nightly
notifications:
    email: false
script:
    - julia -e 'Pkg.init(); Pkg.clone(pwd())'
    - julia -e 'Pkg.add("FactCheck");'
    - julia -e 'Pkg.add("ArrayViews");'
    - julia -e 'Pkg.test("KDTrees", coverage=true)'

after_success:
- julia -e 'cd(Pkg.dir("KDTrees")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
