language: julia
julia:
    - release
    - nightly
notifications:
    email: false
script:
    - julia -e 'Pkg.init(); Pkg.clone(pwd())'
    - julia -e 'using KDtree; @assert isdefined(:KDtree); @assert typeof(KDtree) === Module'
    - julia -e 'Pkg.add("FactCheck");'
    - julia -e 'Pkg.test("KDtree", coverage=true)'

after_success:
- julia -e 'cd(Pkg.dir("KDtree")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
