language: julia
julia:
    - 0.4
    - nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.add("FactCheck");'
    - julia -e 'Pkg.add("Devectorize");'
    - julia -e 'Pkg.clone(pwd()); Pkg.test("KDTrees"; coverage=true)'

after_success:
- julia -e 'cd(Pkg.dir("KDTrees")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
